name: "action-zip"
author: "Monte Hellawell @montudor"
description: "This GitHub action exposes the zip command for use in building/archiving"
branding:
  icon: folder-plus
  color: gray-dark
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  args:
    description: "See montudor/action-zip README.md for more info"
    required: false
